#test yml file

data_dir: '/project/bowmanlab/projects/scratch'
n_epochs: 10
act_map: [0,0,1,1]
lr: 0.0001
n_latent: 50
hidden_layer_sizes: [1000]
em_bounds: [[0.1,0.3],[0.1,0.3],[0.6,0.9],[0.6,0.9]]
do_em: True
em_batch_size: 150
nntype: 'nnutils.sae'
batch_size: 32
batch_output_freq: 500
epoch_output_freq: 2
test_batch_size: 1000
frac_test: 0.1
subsample: 10
outdir: 'sae_e10_lr0001_lat50_rep0_em'
data_in_mem: False
#close_inds_fn: close_inds.npy #Only necessary if using a split autoencoder. np.array of the atom indices that go into classification task. 
#gaussian_labels: False #draw initial labels from a normal distribution
